#!/bin/bash

echo " - Untracked files to be removed -"

git clean -xdn

echo -e "\n - Packages that can be updated -"

ncu

echo -e "\n[enter] to continue. [y + enter] to update package versions and continue."

read -p "" TEST

if [ "$TEST" == "y" ]; then
	echo -e "\nUpdating package.json\n"

	ncu -u
fi

if [ "$1" == "new" ]; then
	echo -e "Removing package-lock.json\n"

	rm -f ./package-lock.json
fi

git clean -xdf

echo -e "\nInstalling packages"

zelda -i