#!/bin/bash

projectFolder=$(cd $(dirname $(readlink -f $0))/.. && pwd)

echo "Updating apt packages"

sudo apt update --fix-missing

sudo dpkg --configure -a

sudo apt upgrade -y

sudo apt install --fix-broken -y

echo "Purgeing apt packages"

sudo apt purge -y

echo "Installing apt packages"

aptPackages="sed"

for package in $aptPackages; do
	if [ "$(dpkg -s $package | grep Status)" != "Status: install ok installed" ]; then sudo apt install -y $package; fi
done

echo "Cleaning apt packages"

sudo apt autoremove -y

sudo apt clean

if [ ! -s "$HOME/.gpioSetup" ]; then
	echo "Configuring GPIO"

	echo -e "\ndtoverlay=gpio-no-irq" | sudo tee -a /boot/config.txt

	echo "SUBSYSTEM==\"bcm2835-gpiomem\", KERNEL==\"gpiomem\", GROUP=\"gpio\", MODE=\"0660\"" | sudo tee /etc/udev/rules.d/20-gpiomem.rules

	echo "1" > $HOME/.gpioSetup
fi

if [ ! -s "$HOME/.oneWireSetup" ]; then
	echo "Configuring GPIO"

	echo -e "\ndtoverlay=w1-gpio" | sudo tee -a /boot/config.txt

	echo "1" > $HOME/.oneWireSetup
fi

if [ ! -s "$HOME/.spiBootSetup" ]; then
	echo "Configuring SPI"

	echo -e "\ndtparam=spi=on" | sudo tee -a /boot/config.txt

	echo "1" > $HOME/.spiBootSetup
fi

if [ ! -s "$HOME/.nvm" ]; then
	echo "Installing NVM"

	curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash

	export NVM_DIR="$HOME/.nvm"

	[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

	nvm install 8

	sudo ln -sf "$NVM_DIR/versions/node/$(nvm version)/bin/node" "/usr/local/bin/node"
	sudo ln -sf "$NVM_DIR/versions/node/$(nvm version)/bin/npm" "/usr/local/bin/npm"

	npm=/usr/local/bin/npm

	sudo setcap 'cap_net_bind_service=+ep' `readlink -f /usr/local/bin/node`
fi

echo "Installing global npm packages"

globalNpmPackages="pm2"

for package in $globalNpmPackages; do
	npm list -g | grep $package || npm i -g $package
done

echo "Installing $projectFolder npm packages"

cd $projectFolder

rm -rf ./node_modules

npm i

if [ ! -s "$HOME/.pm2BootSetup" ]; then
	echo "Configuring PM2"

	pm2 startup

	sudo env PATH=$PATH:$NVM_DIR/versions/node/$(nvm version)/bin $NVM_DIR/versions/node/$(nvm version)/lib/node_modules/pm2/bin/pm2 startup systemd -u $USER --hp $HOME

	pm2 start ./server/index.js

	pm2 save

	echo "1" > $HOME/.pm2BootSetup
fi

echo -e "\nPress enter to reboot now OR Press Ctrl+c to quit and reboot later\n"

read -p ""

sudo reboot